# Generated by Django 3.1.1 on 2020-09-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=50)),
                ('brgy', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('province', models.CharField(default='', max_length=50)),
                ('zip_code', models.IntegerField(default=0)),
                ('birthdate', models.DateField()),
                ('status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow/er'), ('D', 'Divorced')], default='S', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('spouse_name', models.CharField(default='', max_length=50)),
                ('spouse_occupation', models.CharField(default='', max_length=50)),
                ('no_of_children', models.IntegerField()),
                ('mother_name', models.CharField(default='', max_length=50)),
                ('mother_occupation', models.CharField(default='', max_length=50)),
                ('father_name', models.CharField(default='', max_length=50)),
                ('father_occupation', models.CharField(default='', max_length=50)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('religion', models.CharField(default='', max_length=50)),
                ('elementary_school', models.CharField(default='', max_length=50)),
                ('elementary_grade', models.CharField(default='', max_length=50)),
                ('elementary_year_completed', models.IntegerField(default=0)),
                ('elementary_awards', models.TextField(default='')),
                ('junioir_high_school', models.CharField(default='', max_length=50)),
                ('junior_high_grade', models.CharField(default='', max_length=50)),
                ('junior_high_year_completed', models.IntegerField(default=0)),
                ('junior_high_awards', models.TextField(default='')),
                ('senior_high_school', models.CharField(default='', max_length=50)),
                ('senior_high_grade', models.CharField(default='', max_length=50)),
                ('senior_high_year_completed', models.IntegerField(default=0)),
                ('senior_high_awards', models.TextField(default='')),
                ('college_school', models.CharField(default='', max_length=50)),
                ('college_course', models.CharField(default='', max_length=50)),
                ('college_level', models.IntegerField(default=0)),
                ('college_year_completed', models.IntegerField(default=0)),
                ('college_awards', models.TextField(default='')),
                ('post_graduate_school', models.CharField(default='', max_length=50)),
                ('post_graduate_course', models.CharField(default='', max_length=50)),
                ('post_graduate_level', models.IntegerField(default=0)),
                ('post_graduate_year_completed', models.IntegerField(default=0)),
                ('post_graduate_awards', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('sponsor', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('venue', models.CharField(default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customer')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
    ]
