# Generated by Django 3.1.1 on 2020-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200919_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='elementary_grade',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='junior_high_grade',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='senior_high_grade',
            field=models.FloatField(default=1),
        ),
    ]
